language: ruby
services: mongodb
rvm:
  - 2.0.0
  - 1.9.3
  - jruby
gemfile:
  - Gemfile
  - Gemfile.mongoid-two
  - Gemfile.mongoid-three
  - Gemfile.mongoid-four
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: Gemfile
